[window]
opacity = 0.9
decorations = "Full"
decorations_theme_variant = "Dark"

[window.padding]
x = 12
y = 12

[font]
size = 14.0


[colors.primary]
background = "#000000"
foreground = "#cdd6f4"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[colors.normal]
black   = "#000000"
red     = "#f93109"
green   = "#19f909"
yellow  = "#f7ef04"
blue    = "#0602f9"
magenta = "#e807f4"
cyan    = "#07ecf4"
white   = "#f4f4f4"

[colors.bright]
black   = "#000000"
red     = "#f93109"
green   = "#19f909"
yellow  = "#f7ef04"
blue    = "#0602f9"
magenta = "#e807f4"
cyan    = "#07ecf4"
white   = "#f4f4f4"

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]


